version: "3.8"

services:
  nginx:
    build: ./requirements/nginx/
    networks:
      - 42net
    ports:
      - "443:443"
    restart: on-failure
  maraidb:
    build: ./requirements/mariadb/
    networks:
      - 42net
    ports:
      - "3306:3306"
    restart: on-failure

networks:
  42net:
    driver: bridge
