version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    networks:
      - 42net
    volumes:
      - db:/var/lib/mysql
    env_file: .env
    restart: always
 
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    build: ./requirements/wordpress/
    networks:
      - 42net
    volumes:
      - wp:/var/www/html/wordpress
    env_file: .env
    restart: always
 
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    networks:
      - 42net
    volumes:
      - wp:/var/www/html/wordpress
    ports:
      - "443:443"
    restart: always

  adminer:
    container_name: adminer
    depends_on:
      - mariadb
    build: ./bonus/adminer/
    networks:
      - 42net
    ports:
      - "8080:8080"
    restart: always

  redis:
    container_name: redis
    build: ./bonus/redis/
    networks:
      - 42net
    restart: always

  ftp:
    container_name: ftp
    build: ./bonus/ftp/
    networks:
      - 42net
    volumes:
      - wp:/home/$FTP_USER/ftp
    env_file: .env
    ports:
      - "21:21"
    restart: always

  cadvisor:
    container_name: cadvisor
    build: ./bonus/cadvisor/
    networks:
      - 42net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8081:8080"
    restart: always

networks:
  42net:
    name: 42net
    driver: bridge


volumes:
  db:
    name: db
    driver_opts:
      o: bind
      type: none
      device: /home/drohanne/data/mariadb

  wp:
    name: wp
    driver_opts:
      o: bind
      type: none
      device: /home/drohanne/data/wordpress
