# baseURL = "https://your_domain.com/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Lynx"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
   name = "Custom website"
   headline = "Inception - School42"
   # image = "img/author.jpg"  # path relative to static directory

  links = [
     link = { href = "https://drohanne.42.fr", text = "Wordpress" },
     link = { href = "http://localhost:8000", text = "Adminer" },
     link = { href = "https://github.com/jpanther/lynx", text = "Cadvisor" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
